# Unit 23. 2차원 리스트


## 23.1 생성 및 인덱싱


In [5]:
a=[[10, 20], [30, 40],[50,60]]
a

[[10, 20], [30, 40], [50, 60]]

In [9]:
a[0].append(30)
a

[[10, 20, 30, 30], [30, 40], [50, 60]]

In [2]:
#a[행인데스][열인덱스]
a[1][0]

30

In [3]:
import numpy as np
b= np.arange(16).reshape(4,4)
b


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [5]:
b[1,1]

5

In [11]:
b[1:-1,0:-1]

array([[ 4,  5,  6],
       [ 8,  9, 10]])

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [15]:
# 톱니형 리스트
a = [[10, 20],
     [500, 600, 700],
     [9],
     [30, 40],
     [8],
     [800, 900, 1000]]
a

[[10, 20], [500, 600, 700], [9], [30, 40], [8], [800, 900, 1000]]

In [18]:
a=[]
for i in range(4):
  t=[]
  for k in range(4):
    t.append(i*4+k)
  a.append(t)
a

[[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11], [12, 13, 14, 15]]

In [19]:
[[i*4+k for k in range(4)]for i in range(4)]

[[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11], [12, 13, 14, 15]]

In [21]:
from pprint import pprint
pprint(a,indent=4,width=30)

[   [0, 1, 2, 3],
    [4, 5, 6, 7],
    [8, 9, 10, 11],
    [12, 13, 14, 15]]


## 23.2 for 반복문 사용

In [22]:
for row in a:
  print(row)

[0, 1, 2, 3]
[4, 5, 6, 7]
[8, 9, 10, 11]
[12, 13, 14, 15]


In [23]:
for r in a:
  print(r)

[0, 1, 2, 3]
[4, 5, 6, 7]
[8, 9, 10, 11]
[12, 13, 14, 15]


In [26]:
for row in a:
  for element in row:
    print(f'{element:2d}',end='')
  print()

 0 1 2 3
 4 5 6 7
 8 91011
12131415


In [28]:
for w,x,y,z in a:
  print(w,x,y,z)

0 1 2 3
4 5 6 7
8 9 10 11
12 13 14 15


## 23.3 반복문으로 리스트 만들기

In [30]:
a = []    # 빈 리스트 생성
 
for i in range(10):
    a.append(i)    # append로 요소 추가
 
print(a)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [32]:
a=[[0 for _ in range(2)]for _ in range(3)]
a

[[0, 0], [0, 0], [0, 0]]

In [34]:
a=[[0]*2 for _ in range(3)]
a

[[0, 0], [0, 0], [0, 0]]

In [36]:
number=[3,1,3,2,5]

b=[]
for i in number:
  line=[]
  for _ in range(i):
    line.append(0)
  b.append(line)
b

[[0, 0, 0], [0], [0, 0, 0], [0, 0], [0, 0, 0, 0, 0]]

In [37]:
[[0]*i for i in number]

[[0, 0, 0], [0], [0, 0, 0], [0, 0], [0, 0, 0, 0, 0]]

## 23.4 2차원 리스트의 할당과 복사

In [39]:
a=[[10,20],[30,40],[50,60]]
b=a
b[0][0]=500
a

[[500, 20], [30, 40], [50, 60]]

In [40]:
a=[[10,20],[30,40],[50,60]]
import copy
b=copy.deepcopy(a)
b[0][0]=500
a

[[10, 20], [30, 40], [50, 60]]